version: '3.8'

services:
  fama-sistema:
    image: fama-sistema:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    volumes:
      - vol_uploads:/app/uploads
      - vol_logs:/app/logs
    networks:
      - network_public
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        
        # Roteador principal
        - "traefik.http.routers.fama-sistema.rule=Host(`famachat.com.br`)"
        - "traefik.http.routers.fama-sistema.entrypoints=websecure"
        - "traefik.http.routers.fama-sistema.tls=true"
        - "traefik.http.routers.fama-sistema.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.fama-sistema.service=fama-sistema"
        
        # Roteador para www (redirect)
        - "traefik.http.routers.fama-sistema-www.rule=Host(`www.famachat.com.br`)"
        - "traefik.http.routers.fama-sistema-www.entrypoints=websecure"
        - "traefik.http.routers.fama-sistema-www.tls=true"
        - "traefik.http.routers.fama-sistema-www.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.fama-sistema-www.middlewares=redirect-www-to-non-www"
        
        # Middleware para redirect www
        - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.regex=^https://www\\.famachat\\.com\\.br/(.*)"
        - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.replacement=https://famachat.com.br/$${1}"
        - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.permanent=true"
        
        # Serviço
        - "traefik.http.services.fama-sistema.loadbalancer.server.port=3000"
        - "traefik.http.services.fama-sistema.loadbalancer.healthcheck.path=/api/health"
        - "traefik.http.services.fama-sistema.loadbalancer.healthcheck.interval=30s"
        - "traefik.http.services.fama-sistema.loadbalancer.healthcheck.timeout=10s"

volumes:
  vol_uploads:
    external: true
    name: volume_swarm_uploads
  vol_logs:
    external: true
    name: volume_swarm_logs

networks:
  network_public:
    external: true
    name: network_public